<?php

/**
 * Implements hook_entity_info().
 */
function mandrill_activity_entity_info() {
  $return = array(
    'mandrill_activity_entity' => array(
      'label' => t('Mandrill Activity Entity'),
      'controller class' => 'EntityAPIControllerExportable',
      'entity class' => 'MandrillActivityEntity',
      'base table' => 'mandrill_activity_entity',
      'uri callback' => 'entity_class_uri',
      'fieldable' => FALSE,
      'exportable' => TRUE,
      'module' => 'mandrill_activity',
      'entity keys' => array(
        'id' => 'mandrill_activity_entity_id',
        'name' => 'name',
        'label' => 'label',
      ),
      // Enable the entity API's admin UI.
      'admin ui' => array(
        'path' => 'admin/config/services/mandrill/activity',
        'file' => 'mandrill_activity.admin.inc',
        'controller class' => 'MandrillActivityUIController',
      ),
      'label callback' => 'entity_class_label',
      'access callback' => 'mandrill_activity_entity_access',
    ),
  );

  return $return;
}

/**
 * Access callback for mandrill_activity_entity.
 */
function mandrill_activity_entity_access() {
  return user_access('administer mandrill activity');
}

/**
 * Implements hook_menu().
 */
function mandrill_activity_menu() {
  $items = array();
  $mandrill_activity_entities = mandrill_activity_load();
  foreach ($mandrill_activity_entities as $mandrill_activity_entity) {
    $arg = substr_count($mandrill_activity_entity->entity_path, '/');
    $items[$mandrill_activity_entity->entity_path . '%entity_object/mandrill_activity'] = array(
      'title' => 'Mandrill Activity',
      'load arguments' => array($mandrill_activity_entity->entity_type),
      'page callback' => 'mandrill_activity_page',
      'page arguments' => array($arg, $mandrill_activity_entity),
      'access callback' => 'mandrill_activity_access',
      'access arguments' => array($mandrill_activity_entity),
      'type' => MENU_LOCAL_TASK,
    );
  }

  return $items;
}

/**
 * Access callback for activity menu items.
 */
function mandrill_activity_access(MandrillActivityEntity $mandrill_activity_entity) {
  if ($mandrill_activity_entity->enabled && user_access('access Mandrill activity')) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Loads a single mandrill_activity_entity or all of them if no name provided.
 *
 * @param null $name
 *
 * @return array
 */
function mandrill_activity_load($name = NULL) {
  $types = entity_load_multiple_by_name('mandrill_activity_entity', isset($name) ? array($name) : FALSE);
  return isset($name) ? reset($types) : $types;
}

/**
 * Content for the Mandrill log tab on entity instance pages.
 *
 * @object $entity
 *   Entity to load activity for.
 * @param MandrillActivityEntity $mandrill_activity_entity
 *   Loaded MandrillActivityEntity object.
 *
 * @return array
 *   Render array.
 */
function mandrill_activity_page($entity, MandrillActivityEntity $mandrill_activity_entity) {
  $entity_wrapper = entity_metadata_wrapper($mandrill_activity_entity->entity_type, $entity);
  $email_property = $mandrill_activity_entity->email_property;
  $email_property_array = explode(':', $email_property);
  $parent = $entity_wrapper;
  foreach ($email_property_array as $drupal_field) {
    if ($parent instanceof EntityListWrapper) {
      $child_wrapper = $parent->get(0)->{$drupal_field};
    }
    else {
      $child_wrapper = $parent->{$drupal_field};
    }
    $parent = $child_wrapper;
  }
  $email = $parent->value();
  // Validate email address.
  if (!valid_email_address($email)) {
    return array(
      'error_notice' => array(
        '#markup' => t('%email does not contain a valid email address. Unable to lookup Mandrill activity history without a valid email.',
          array('%email' => $email_property)
        ),
      ),
    );
  }

  $header = array(
    t('Campaign'),
    t('Action'),
    t('Date & Time'),
  );
  $rows = array();

  // Loop through all activities, creating rows for each.
  $user_activity = mandrill_activity_get_activity($email);
  if (isset($user_activity['lists'])) {
    foreach ($user_activity['lists'] as $list_activity) {
      $rows[] = array(
        'no_striping' => TRUE,
        'data' => array(
          array(
            'data' => '<strong>List: ' . $list_activity['list']['name'] . '</strong>',
            'colspan' => count($header),
            'style' => 'text-align:center',
          ),
        ),
      );

      foreach ($list_activity['activity'] as $activity) {
        $rows[] = array(
          array(
            'data' => array(
              '#type' => 'link',
              '#title' => $user_activity['campaigns'][$activity['campaign_id']]['title'],
              '#href' => $user_activity['campaigns'][$activity['campaign_id']]['archive_url'],
            ),
          ),
          $activity['action'],
          $activity['timestamp'],
        );
      }
    }
  }

  $display['mandrill_activity'] = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $rows,
  );
  return $display;
}


/**
 * Return all activity on all lists for a given email address.
 *
 * @string $email
 *   Email to load Mandrill activity for.
 *
 * @return array
 *   Array of activity.
 */
function mandrill_activity_get_activity($email) {
  $activity = array();

  $mandrill = mandrill_get_api_object();
  $result = $mandrill->messages_search("email:{$email}");

  $listdata = Mandrill_get_lists_by_email($email);
  if (isset($listdata['campaigns'])) {
    $all_activity['campaigns'] = $listdata['campaigns'];
  }
  if (isset($listdata['lists'])) {
    foreach ($listdata['lists'] as $list) {
      $all_activity['lists'][$list['id']] = array(
        'list' => $list,
        'activity' => mandrill_activity_get_member_activity($list['id'], $email)
      );
    }
  }

  return $all_activity;
}

/**
 * Implements hook_permission().
 */
function mandrill_activity_permission() {
  $return = array();

  $return['access mandrill activity'] = array(
    'title' => t('Access Mandrill activity'),
    'description' => t('View own Mandrill activity history.'),
  );
  $return['administer mandrill activity'] = array(
    'title' => t('Administer Mandrill activity entities'),
    'description' => t('Add, Delete, and Configure Mandrill Activity entity settings.'),
  );
  return $return;
}
