<?php

/**
 * Implements hook_menu().
 */
function mandrill_reports_menu() {
  $items = array();
  $items['admin/reports/mandrill'] = array(
    'title' => 'Mandrill Reports',
    'page callback' => 'mandrill_reports_page',
    'access arguments' => array('administer mandrill'),
    'description' => 'View Mandrill reports.',
  );
  $items['admin/reports/mandrill/stats'] = array(
    'title' => 'Stats',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  return $items;
}

/**
 * Return an associative array containing raw stats.
 *
 * @return array
 */
function mandrill_reports_data() {
  $api = mandrill_get_api_object();

  $data = array();

  // basic user info
  $data['user'] = $api->users_info();

  // tags
  $tags = $api->tags_list();
  foreach ($tags as $tag) {
    $data['tags'][$tag['tag']] = $api->tags_info($tag['tag']);
    $data['tags'][$tag['tag']]['time_series'] = $api->tags_time_series($tag['tag']);
  }

  // all time
  $data['all_time_series'] = $api->tags_all_time_series();

  // senders
  $senders = $api->senders_list();
  foreach ($senders as $sender) {
    $data['senders'][$sender['address']] = $api->senders_info($sender['address']);
    $data['senders'][$sender['address']]['time_series'] = $api->senders_time_series($sender['address']);
  }

  // urls
  $urls = $api->urls_list();
  foreach ($urls as $url) {
    $data['urls'][$url['url']] = $url;
    $data['urls'][$url['url']]['time_series'] = $api->urls_time_series($url['url']);
  }

  return $data;
}

/**
 * Page callback for rendering stats.
 *
 * @return array
 */
function mandrill_reports_page() {
  $data = mandrill_reports_data();
  foreach ($data['all_time_series'] as $series) {
    $time = strtotime($series['time']);
    $settings['mandrill_reports']['volume'][] = array(
      'date' => $time,
      'delivered' => $series['sent'],
      'bounced' => $series['hard_bounces'] + $series['soft_bounces'],
      'rejected' => $series['rejects']
    );
    $settings['mandrill_reports']['engagement'][] = array(
      'date' => $time,
      'open_rate' => $series['unique_opens']/$series['sent'],
      'click_rate' => $series['unique_clicks']/$series['sent']
    );
  }

  // sort by timestamp of the results
  sort($settings['mandrill_reports']['volume']);
  sort($settings['mandrill_reports']['engagement']);

  $path = drupal_get_path('module', 'mandrill_reports');
  $render = array(
    '#attached' => array(
      'js' => array(
        $path . '/amcharts.js',
        $path . '/mandrill_reports.js',
        array(
          'type' => 'setting',
          'data' => $settings,
        )
      )
    ),
    'volume' => array(
      '#prefix' => '<h2>' . t('Sending Volume') . '</h2>',
      '#markup' => '<div id="volume-chart"></div>'
    ),
    'engagement' => array(
      '#prefix' => '<h2>' . t('Average Open and Click Rate') . '</h2>',
      '#markup' => '<div id="engage-chart"></div>'
    ),
    'urls' => array(
      '#prefix' => '<h2>' . t('Tracked URLs') . '</h2>',
      '#markup' => '<div id="url-chart"></div>'
    ),
  );

  return $render;
}
